# -*- encoding: utf-8 -*-
#
=begin
#Siwapp API Client

#Access Siwapp data via API.

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# $:.push File.expand_path("../lib", __FILE__)
# require "siwapp-client/version"
require 'json'

Gem::Specification.new do |s|
  s.name        = "siwapp-client"
  s.version     = JSON.parse(File.read('siwapp_api.json'))["info"]["version"]
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Sology"]
  s.email       = ["wojtek@sology.eu"]
  s.homepage    = "https://github.com/Sology/siwapp-api-ruby-client"
  s.summary     = "Siwapp API Client Ruby Gem"
  s.description = "Access Siwapp data via API."
  # TODO uncommnet and update below with a proper license 
  #s.license     = "Apache 2.0"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 1.7'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = `ruby generate_ruby_client.rb | find ./ruby-client/*`.split("\n").uniq.sort.select{|f| !f.empty? }
  s.test_files    = `find ./ruby-client/spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["./ruby-client/lib"]
end
